# Generated by Django 5.1.3 on 2024-11-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='product_files/'),
        ),
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(default='http://www.google.com'),
            preserve_default=False,
        ),
    ]
